name: Assets Update to WordPress.org

on:
  push:
    branches: [ dev ]

jobs:
  assets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Assets Update
        id: assets
        uses: 10up/action-wordpress-plugin-asset-update@2.2.0
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
